/// Calendário contínuo 2024–2026, marcado como tabela de datas.
table 'dCalendario'
	lineageTag: 37889d74-13ae-5969-97c5-70eb4b6837fe
	dataCategory: Time

	column 'Data'
		isKey
		dataType: dateTime
		sourceColumn: Data
		summarizeBy: none
		lineageTag: b469656d-ade4-5cce-bf31-a57ab1f07d5c
		formatString: dd/MM/yyyy

	column 'Ano'
		dataType: int64
		sourceColumn: Ano
		summarizeBy: none
		lineageTag: b2a59681-ce85-5d31-be21-7ed7ad265612

	column 'MesNumero'
		dataType: int64
		sourceColumn: MesNumero
		summarizeBy: none
		lineageTag: 855dd845-2aa5-585c-801f-1929116eaa6b
		isHidden

	column 'Mes'
		dataType: string
		sourceColumn: Mes
		summarizeBy: none
		lineageTag: ddb69b0c-6366-55d6-bf36-67f1c37295a7
		sortByColumn: 'MesNumero'

	column 'MesAbrev'
		dataType: string
		sourceColumn: MesAbrev
		summarizeBy: none
		lineageTag: e54e9010-0f1d-5271-8b70-800527017f3c
		sortByColumn: 'MesNumero'

	column 'AnoMes'
		dataType: string
		sourceColumn: AnoMes
		summarizeBy: none
		lineageTag: 42f3691d-a286-5889-b703-d8447c818bb7
		sortByColumn: 'OrdemAnoMes'

	column 'OrdemAnoMes'
		dataType: int64
		sourceColumn: OrdemAnoMes
		summarizeBy: none
		lineageTag: a7be499f-f302-5ae2-b992-d55ac65fa19b
		isHidden

	column 'Trimestre'
		dataType: string
		sourceColumn: Trimestre
		summarizeBy: none
		lineageTag: e05f4de1-264b-50f1-b49b-4b66bf65f147

	column 'Semestre'
		dataType: string
		sourceColumn: Semestre
		summarizeBy: none
		lineageTag: bc27700c-e4d7-5a41-bfec-fea3034721a0

	annotation __PBI_TimeIntelligenceEnabled = 0

	partition 'dCalendario' = m
		mode: import
		queryGroup: '01_Dimensoes'
		source =
			let
			    Inicio = #date(2024,1,1),
			    Fim = #date(2026,12,31),
			    Fonte = Table.FromList(List.Dates(Inicio,Duration.Days(Fim-Inicio)+1,#duration(1,0,0,0)),Splitter.SplitByNothing(),{"Data"}),
			    Tipos = Table.TransformColumnTypes(Fonte,{{"Data",type date}}),
			    Ano = Table.AddColumn(Tipos,"Ano",each Date.Year([Data]),Int64.Type),
			    MesNumero = Table.AddColumn(Ano,"MesNumero",each Date.Month([Data]),Int64.Type),
			    Mes = Table.AddColumn(MesNumero,"Mes",each Date.ToText([Data],"MMMM","pt-BR"),type text),
			    MesAbrev = Table.AddColumn(Mes,"MesAbrev",each Text.Proper(Date.ToText([Data],"MMM","pt-BR")),type text),
			    AnoMes = Table.AddColumn(MesAbrev,"AnoMes",each Date.ToText([Data],"yyyy-MM"),type text),
			    OrdemAnoMes = Table.AddColumn(AnoMes,"OrdemAnoMes",each [Ano]*100+[MesNumero],Int64.Type),
			    Trimestre = Table.AddColumn(OrdemAnoMes,"Trimestre",each "T" & Text.From(Date.QuarterOfYear([Data])),type text),
			    Semestre = Table.AddColumn(Trimestre,"Semestre",each if [MesNumero]<=6 then "S1" else "S2",type text)
			in
			    Semestre

	annotation PBI_NavigationStepName = Navigation
	annotation PBI_ResultType = Table
