let
    Fonte = fnPlanilha("12_MODELO"),
    Tipos = Table.TransformColumnTypes(Fonte,{{"Data",type date},{"Cenario",type text},{"ReceitaBruta",type number},{"Deducoes",type number},{"ReceitaLiquida",type number},{"CMV",type number},{"LucroBruto",type number},{"Pessoal",type number},{"Comercial",type number},{"Administrativo",type number},{"Tecnologia",type number},{"Logistica",type number},{"Opex",type number},{"EBITDA",type number},{"Depreciacao",type number},{"EBIT",type number},{"Juros",type number},{"LAIR",type number},{"IRSimulado",type number},{"LucroLiquido",type number},{"Clientes",type number},{"Estoque",type number},{"Compras",type number},{"Fornecedores",type number},{"SalariosPagar",type number},{"TributosVendaPagar",type number},{"IRPagar",type number},{"Capex",type number},{"ImobilizadoBruto",type number},{"DepAcumulada",type number},{"Captacao",type number},{"Amortizacao",type number},{"Divida",type number},{"Dividendos",type number},{"Capital",type number},{"LucrosAcumulados",type number},{"Recebimentos",type number},{"PagFornecedores",type number},{"PagOpex",type number},{"PagTributosVenda",type number},{"PagIR",type number},{"FCO_Direto",type number},{"FCO_Indireto",type number},{"FCI",type number},{"FCF",type number},{"VariacaoCaixa",type number},{"CaixaInicial",type number},{"CaixaFinal",type number},{"Ativo",type number},{"Passivo",type number},{"PL",type number},{"CheckBP",type number},{"CheckDFC",type number},{"DSO",type number},{"DIO",type number},{"DPO",type number},{"TaxaVenda",type number},{"TaxaIR",type number},{"TaxaJuros",type number},{"TaxaDep",type number},{"MargemEBITDA",type number},{"MargemLiquida",type number},{"FC_Livre",type number},{"NCG",type number},{"DividaLiquida",type number},{"CheckDiario",type number},{"AtivoCirculante",type number},{"AtivoNaoCirculante",type number},{"DividaCP",type number},{"DividaLP",type number},{"PassivoCirculante",type number},{"PassivoNaoCirculante",type number},{"LiquidezCorrente",type number}},"pt-BR")
in
    Tipos
